---
title: "Assignment 4"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 1 Herd Immunity Threshold

Looking at the plot, we can see that for $R_0$ below 1, the epidemic fails to spread in the population and a negligible fraction becomes infected. Above $R_0=1$, the fraction of the population becoming infected increases rapidly. Diseases like the flu with an $R_0$ between 1.2 and 3 are expected to infect between $31\%$ and $94\%$ of the population, while rubella ($R_0 \in [6,8]$) would be expected to infect over $99.7\%$ and measles ($R_0\in[16,18]$) would infect basically the entire population.
As we can see in the second line in the plot generated by the code in "Newtons_method.r", the fraction of the population required to be immune to stop the pandemic grows similarly with the $R_0$ but is significantly lower. For a flu with $R_0=1.2$, only $16\%$ of the population would need to be immune, while for measles the requirement is $94\%$. Of course this can be a combination of previously infected and vaccinated individuals. These curves have great influence on our epidemic management because it shows us what level of immunity we can expect to aim for with vaccination campaigns.

## Exercise 2: epidemic dynamics
The plots generated by "Epidemic_Dynamics_deSolve.R" shows an epidemic in a population of 100,000 starting with 10 infected individuals and following the parameter values of measles ($R_0=18,\gamma=0.2$). As we see, the growth in infected individuals is slowed down by the 20\% of individuals recovering during each time step. After 5 days 208 individuals have recovered, after 10 days it is already 854.

##  SIR competition
Using invasion analysis, we can show that for one pathogen to invade another in a SIR model with demography and no coinfection, it needs to have a higher R0. We could also formally show that when there are two competing pathogens with different R0 values in this model, the one with the greater R0 will outcompete the other. How is this result consistent with the competitive exclusion principle? Use mathematical notation and explain in terms of the resource use of each species. 

The competitive exclusion principle states that two species with the same niche cannot coexist in the long term. If we take the resource -in this case the susceptible population- as the niche, two species of virus would be considered occupying the same niche, if there is no other dimension to it and we expect the one with the higher efficiency of exploiting the resource to win.
Mathematically speaking, the resource use of each species is described by $\beta I S$, and since $R_0=\frac{\beta}{\mu+\gamma}$, there is a linear relationship between $R_0$ and the efficiency of exploiting the resource.
Another way to think about it is in terms of the equilibrium as we have shown before that for two competing species, the one with the lower equilibrium will be the winner. Since $S^*=\frac{\mu+\gamma}{\beta}$, $R_0$ is inversely related to the endemic equilibrium.
